/**
 * ATS Orchestrator — runs the full six-agent pipeline (doc § 7.2).
 *
 * Pipeline phases:
 *   Phase 1: Data Agent     — fetch prices + news
 *   Phase 2: Parallel       — Regime + Signal + Graph agents
 *   Phase 3: Risk Agent     — Kelly sizing + veto check
 *   Phase 4: Consensus      — apply voting matrix, reach decision
 *   Phase 5: Execution      — (autonomous mode) sign + submit swap
 *   Phase 6: Persist        — write Decision Receipt to Supabase
 *
 * Mode branching:
 *   autonomous  — full pipeline including execution
 *   assisted    — research + sizing; execution requires user approval
 *   solo        — research only; no execution invocation
 *
 * The `emit` callback is called synchronously with each RunEvent so the
 * caller (SSE route) can forward events to the client in real time.
 *
 * Returns the final DecisionReceipt (also persisted to Supabase).
 */

import type {
  RunEvent,
  DecisionReceipt,
  AgentVote,
  Consensus,
  Decision,
  Mode,
  Regime,
  CausalChainAnalysis,
  RiskSizing,
} from '@/lib/ats/types'
import { createSupabaseAdminClient } from '@/lib/supabase/server'

import { runDataAgent } from '@/lib/ats/agents/data-agent'
import { runRegimeAgent } from '@/lib/ats/agents/regime-agent'
import { runSignalAgent } from '@/lib/ats/agents/signal-agent'
import { runGraphAgent } from '@/lib/ats/agents/graph-agent'
import { runRiskAgent } from '@/lib/ats/agents/risk-agent'
import { runExecutionAgent } from '@/lib/ats/agents/execution-agent'

// ── Public input type ─────────────────────────────────────────────────────────

export interface OrchestratorInput {
  /** Unique run ID — generated by caller (e.g. SSE route) */
  run_id: string
  /** User's natural language query */
  query: string
  /** Primary ticker to analyse */
  ticker: string
  /** Trading mode from user_settings */
  mode: Mode
  /** Authenticated user EVM address */
  userWallet: string
  /** Chain to use for execution */
  chainId: number
  /** Optional: approved by user (relevant in assisted mode) */
  executionApproved?: boolean
  /** Optional: estimated agent wallet USD balance for Kelly sizing */
  agentBalanceUSD?: number
}

// ── Consensus matrix ──────────────────────────────────────────────────────────

const AGENT_WEIGHTS: Partial<Record<AgentVote['agent'], number>> = {
  signal:  0.35,
  regime:  0.25,
  graph:   0.20,
  risk:    0.20,
}

function applyConsensus(votes: AgentVote[]): Consensus {
  // If any agent has vetoed, propagate VETO immediately
  const vetoedAgent = votes.find((v) => v.vetoed)
  if (vetoedAgent) {
    return {
      decision: 'VETO',
      confidence: 1.0,
      rationale: `Veto triggered by ${vetoedAgent.agent}: ${vetoedAgent.rationale}`,
      approved_by: [],
      vetoed_by: [vetoedAgent.agent],
    }
  }

  // Weighted vote tally (BUY = +1, SELL = -1, HOLD/ABSTAIN = 0)
  let weightedScore = 0
  let totalWeight = 0

  const approvedBy: AgentVote['agent'][] = []
  const vetoedBy: AgentVote['agent'][] = []

  for (const vote of votes) {
    const weight = AGENT_WEIGHTS[vote.agent] ?? 0.10
    const direction = vote.vote === 'BUY' ? 1 : vote.vote === 'SELL' ? -1 : 0
    weightedScore += direction * weight * vote.confidence
    totalWeight += weight
  }

  const normScore = totalWeight > 0 ? weightedScore / totalWeight : 0

  let decision: Decision
  if (normScore > 0.12) decision = 'BUY'
  else if (normScore < -0.12) decision = 'SELL'
  else decision = 'HOLD'

  // Build approved_by / vetoed_by lists
  for (const vote of votes) {
    const aligned =
      (decision === 'BUY' && vote.vote === 'BUY') ||
      (decision === 'SELL' && vote.vote === 'SELL') ||
      (decision === 'HOLD' && (vote.vote === 'HOLD' || vote.vote === 'ABSTAIN'))
    if (aligned) approvedBy.push(vote.agent)
    else vetoedBy.push(vote.agent)
  }

  const confidence = Math.min(0.95, 0.40 + Math.abs(normScore) * 1.2)

  const dirLabel = decision === 'BUY' ? 'bullish' : decision === 'SELL' ? 'bearish' : 'neutral'
  const rationale =
    `Weighted consensus score ${normScore.toFixed(3)} — ${approvedBy.length} agent(s) align with the ${dirLabel} thesis.`

  return { decision, confidence, rationale, approved_by: approvedBy, vetoed_by: vetoedBy }
}

// ── Supabase persistence ──────────────────────────────────────────────────────

async function persistReceipt(receipt: DecisionReceipt): Promise<string | null> {
  try {
    const supabase = createSupabaseAdminClient()
    const { data, error } = await supabase
      .from('ats_receipts')
      .insert({
        run_id:            receipt.run_id,
        user_wallet:       receipt.user_wallet.toLowerCase(),
        ticker:            receipt.ticker,
        trigger_type:      receipt.trigger_type,
        chain_id:          receipt.chain_id,
        tx_hash:           receipt.tx_hash ?? null,
        storage_root_hash: receipt.storage_root_hash ?? null,
        agent_votes:       receipt.agent_votes as unknown as Record<string, unknown>[],
        regime:            receipt.regime,
        causal_chain:      receipt.causal_chain as unknown as Record<string, unknown>,
        risk_sizing:       receipt.risk_sizing as unknown as Record<string, unknown>,
        consensus:         receipt.consensus as unknown as Record<string, unknown>,
      })
      .select('id')
      .single()

    if (error) {
      console.error('[ATS] Failed to persist receipt:', error.message)
      return null
    }

    return data?.id ?? null
  } catch (err) {
    console.error('[ATS] Receipt persistence error:', err)
    return null
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Runs the complete ATS pipeline and returns the Decision Receipt.
 *
 * @param input   OrchestratorInput with query, ticker, mode, userWallet, etc.
 * @param emit    Callback invoked synchronously with each RunEvent.
 */
export async function runOrchestrator(
  input: OrchestratorInput,
  emit: (event: RunEvent) => void,
): Promise<DecisionReceipt> {
  const { run_id, query, ticker, mode, userWallet, chainId } = input
  const ts = () => new Date().toISOString()

  // ── run.start ────────────────────────────────────────────────────────────
  emit({
    type: 'run.start',
    run_id,
    ts: ts(),
    message: `ATS run started — analysing ${ticker.toUpperCase()} (${mode} mode)`,
    payload: { ticker, mode, chain_id: chainId, query },
  })

  let allVotes: AgentVote[] = []
  let regime: Regime = 'sideways'
  let causal: CausalChainAnalysis = { active_chains: [], net_directional_bias: 'neutral' }
  let riskSizing: RiskSizing = { kelly_fraction: 0, size_usd: 0, max_loss_usd: 0, veto_triggered: true, veto_reason: 'Initialising' }
  let consensus: Consensus = { decision: 'HOLD', confidence: 0.5, rationale: '', approved_by: [], vetoed_by: [] }
  let txHash: string | null = null

  try {
    // ── Phase 1: Data Agent ───────────────────────────────────────────────
    const { data, news } = await runDataAgent(ticker, emit, run_id)

    if (data.quality_score === 0) {
      throw new Error(`No price data found for ticker "${ticker}". Check the ticker symbol.`)
    }

    // ── Phase 2: Regime + Signal + Graph (parallel) ───────────────────────
    const [regimeResult, signalResult, graphResult] = await Promise.all([
      runRegimeAgent(data, news, userWallet, emit, run_id),
      runSignalAgent(data, news, regime, userWallet, emit, run_id),  // uses sideways as initial regime
      runGraphAgent(data, regime, userWallet, emit, run_id),
    ])

    regime = regimeResult.regime
    causal = signalResult.causal

    // Collect votes from Phase 2 (exclude risk which hasn't run yet)
    const phase2Votes: AgentVote[] = [
      regimeResult.vote,
      signalResult.vote,
      graphResult.vote,
    ]

    // ── Phase 3: Risk Agent ───────────────────────────────────────────────
    const riskResult = await runRiskAgent(
      data,
      phase2Votes,
      signalResult.technical,
      input.agentBalanceUSD,
      emit,
      run_id,
    )

    riskSizing = riskResult.sizing
    allVotes = [...phase2Votes, riskResult.vote]

    // ── Phase 4: Consensus ────────────────────────────────────────────────
    consensus = applyConsensus(allVotes)

    emit({
      type: 'consensus.reached',
      run_id,
      ts: ts(),
      agent: 'orchestrator',
      message: `Consensus: ${consensus.decision} (confidence ${(consensus.confidence * 100).toFixed(0)}%) — ${consensus.rationale}`,
      payload: {
        decision: consensus.decision,
        confidence: consensus.confidence,
        approved_by: consensus.approved_by,
        vetoed_by: consensus.vetoed_by,
      },
    })

    // ── Phase 5: Execution (autonomous / assisted+approved) ───────────────
    const shouldExecute =
      (mode === 'autonomous' || (mode === 'assisted' && input.executionApproved === true)) &&
      (consensus.decision === 'BUY' || consensus.decision === 'SELL') &&
      !riskSizing.veto_triggered

    if (shouldExecute) {
      const execResult = await runExecutionAgent(
        ticker,
        consensus.decision as 'BUY' | 'SELL',
        riskSizing,
        userWallet,
        chainId,
        emit,
        run_id,
      )
      txHash = execResult.tx_hash
    } else if (mode === 'solo' || consensus.decision === 'HOLD' || consensus.decision === 'VETO') {
      emit({
        type: 'execution.done',
        run_id,
        ts: ts(),
        agent: 'execution',
        message: mode === 'solo'
          ? 'Solo mode — execution skipped, research complete.'
          : `No execution: consensus is ${consensus.decision}.`,
        payload: { skipped: true, reason: mode === 'solo' ? 'solo_mode' : consensus.decision },
      })
    } else if (mode === 'assisted' && !input.executionApproved) {
      emit({
        type: 'execution.pending',
        run_id,
        ts: ts(),
        agent: 'execution',
        message: `Assisted mode — awaiting user approval to execute ${consensus.decision} $${riskSizing.size_usd.toFixed(2)}.`,
        payload: { awaiting_approval: true, decision: consensus.decision, size_usd: riskSizing.size_usd },
      })
    }

  } catch (err) {
    const errMsg = err instanceof Error ? err.message : String(err)
    emit({
      type: 'run.error',
      run_id,
      ts: ts(),
      agent: 'orchestrator',
      message: `Run failed: ${errMsg}`,
      payload: { error: errMsg },
    })

    consensus = {
      decision: 'HOLD',
      confidence: 0,
      rationale: `Run aborted: ${errMsg}`,
      approved_by: [],
      vetoed_by: [],
    }
  }

  // ── Phase 6: Persist receipt ──────────────────────────────────────────────
  const receipt: DecisionReceipt = {
    run_id,
    user_wallet: userWallet.toLowerCase(),
    ticker: ticker.toUpperCase(),
    trigger_type: 'user_query',
    query,
    chain_id: chainId,
    tx_hash: txHash,
    storage_root_hash: null,
    agent_votes: allVotes,
    regime,
    causal_chain: causal,
    risk_sizing: riskSizing,
    consensus,
    proof_ref: null,
  }

  const receiptId = await persistReceipt(receipt)
  if (receiptId) receipt.id = receiptId

  emit({
    type: 'run.done',
    run_id,
    ts: ts(),
    agent: 'orchestrator',
    message: `Run complete — decision: ${consensus.decision} · receipt ${receiptId ?? 'unsaved'}`,
    receipt,
  })

  return receipt
}
