import { BlockTemplate } from '@/types/agent-builder';

export const BLOCK_TEMPLATES: BlockTemplate[] = [
  // TRIGGER BLOCKS
  {
    type: 'trigger',
    subType: 'price_threshold',
    label: 'Price Threshold',
    description: 'Trigger when price reaches a specific value',
    icon: 'Target',
    color: '#10b981',
    category: 'Triggers',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true, placeholder: 'Select token' },
      { name: 'condition', type: 'select', value: 'above', required: true, options: ['above', 'below', 'equals'] },
      { name: 'price', type: 'number', value: 0, required: true, min: 0, step: 0.01, placeholder: 'Enter price' },
    ],
  },
  {
    type: 'trigger',
    subType: 'price_change',
    label: 'Price Change %',
    description: 'Trigger on percentage price change',
    icon: 'TrendingUp',
    color: '#10b981',
    category: 'Triggers',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true, placeholder: 'Select token' },
      { name: 'direction', type: 'select', value: 'increase', required: true, options: ['increase', 'decrease', 'any'] },
      { name: 'percentage', type: 'percentage', value: 5, required: true, min: 0, max: 100, step: 0.1 },
      { name: 'timeframe', type: 'select', value: '1h', required: true, options: ['1m', '5m', '15m', '1h', '4h', '24h'] },
    ],
  },
  {
    type: 'trigger',
    subType: 'time_based',
    label: 'Time Schedule',
    description: 'Trigger at specific time intervals',
    icon: 'Clock',
    color: '#10b981',
    category: 'Triggers',
    defaultParameters: [
      { name: 'interval', type: 'select', value: 'daily', required: true, options: ['every_minute', 'hourly', 'daily', 'weekly'] },
      { name: 'time', type: 'time', value: '09:00', required: false, placeholder: 'HH:MM' },
    ],
  },
  {
    type: 'trigger',
    subType: 'manual',
    label: 'Manual Trigger',
    description: 'Start manually by user',
    icon: 'Play',
    color: '#10b981',
    category: 'Triggers',
    defaultParameters: [],
  },

  // CONDITION BLOCKS
  {
    type: 'condition',
    subType: 'if_else',
    label: 'If/Else',
    description: 'Branch based on condition',
    icon: 'GitBranch',
    color: '#f59e0b',
    category: 'Conditions',
    defaultParameters: [
      { name: 'condition', type: 'select', value: 'price_above', required: true, 
        options: ['price_above', 'price_below', 'volume_above', 'balance_above', 'custom'] },
      { name: 'value', type: 'number', value: 0, required: true, step: 0.01 },
    ],
  },
  {
    type: 'condition',
    subType: 'compare',
    label: 'Compare Values',
    description: 'Compare two values',
    icon: 'Scale',
    color: '#f59e0b',
    category: 'Conditions',
    defaultParameters: [
      { name: 'valueA', type: 'string', value: '', required: true, placeholder: 'Value A' },
      { name: 'operator', type: 'select', value: '>', required: true, options: ['>', '<', '>=', '<=', '==', '!='] },
      { name: 'valueB', type: 'string', value: '', required: true, placeholder: 'Value B' },
    ],
  },
  {
    type: 'condition',
    subType: 'range_check',
    label: 'Range Check',
    description: 'Check if value is within range',
    icon: 'Ruler',
    color: '#f59e0b',
    category: 'Conditions',
    defaultParameters: [
      { name: 'value', type: 'string', value: '', required: true, placeholder: 'Value to check' },
      { name: 'min', type: 'number', value: 0, required: true },
      { name: 'max', type: 'number', value: 100, required: true },
    ],
  },

  // ACTION BLOCKS
  {
    type: 'action',
    subType: 'buy',
    label: 'Buy Token',
    description: 'Execute buy order',
    icon: 'ShoppingCart',
    color: '#3b82f6',
    category: 'Actions',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true, placeholder: 'Token to buy' },
      { name: 'amountType', type: 'select', value: 'fixed', required: true, options: ['fixed', 'percentage', 'all'] },
      { name: 'amount', type: 'number', value: 0, required: true, min: 0, step: 0.01 },
      { name: 'slippage', type: 'percentage', value: 1, required: true, min: 0.1, max: 50, step: 0.1 },
    ],
  },
  {
    type: 'action',
    subType: 'sell',
    label: 'Sell Token',
    description: 'Execute sell order',
    icon: 'DollarSign',
    color: '#3b82f6',
    category: 'Actions',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true, placeholder: 'Token to sell' },
      { name: 'amountType', type: 'select', value: 'fixed', required: true, options: ['fixed', 'percentage', 'all'] },
      { name: 'amount', type: 'number', value: 0, required: true, min: 0, step: 0.01 },
      { name: 'slippage', type: 'percentage', value: 1, required: true, min: 0.1, max: 50, step: 0.1 },
    ],
  },
  {
    type: 'action',
    subType: 'swap',
    label: 'Swap Tokens',
    description: 'Swap between two tokens',
    icon: 'ArrowLeftRight',
    color: '#3b82f6',
    category: 'Actions',
    defaultParameters: [
      { name: 'fromToken', type: 'token', value: '', required: true, placeholder: 'From token' },
      { name: 'toToken', type: 'token', value: '', required: true, placeholder: 'To token' },
      { name: 'amount', type: 'number', value: 0, required: true, min: 0, step: 0.01 },
      { name: 'slippage', type: 'percentage', value: 1, required: true, min: 0.1, max: 50, step: 0.1 },
    ],
  },
  {
    type: 'action',
    subType: 'stop_loss',
    label: 'Stop Loss',
    description: 'Set stop loss order',
    icon: 'Shield',
    color: '#3b82f6',
    category: 'Actions',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'triggerPrice', type: 'number', value: 0, required: true, min: 0, step: 0.01 },
      { name: 'sellPercentage', type: 'percentage', value: 100, required: true, min: 1, max: 100 },
    ],
  },
  {
    type: 'action',
    subType: 'take_profit',
    label: 'Take Profit',
    description: 'Set take profit order',
    icon: 'TrendingUp',
    color: '#3b82f6',
    category: 'Actions',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'triggerPrice', type: 'number', value: 0, required: true, min: 0, step: 0.01 },
      { name: 'sellPercentage', type: 'percentage', value: 50, required: true, min: 1, max: 100 },
    ],
  },

  // STRATEGY BLOCKS
  {
    type: 'strategy',
    subType: 'dca',
    label: 'DCA Strategy',
    description: 'Dollar Cost Averaging',
    icon: 'Layers',
    color: '#8b5cf6',
    category: 'Strategies',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'amount', type: 'number', value: 100, required: true, min: 0 },
      { name: 'interval', type: 'select', value: 'daily', required: true, options: ['hourly', 'daily', 'weekly', 'monthly'] },
      { name: 'duration', type: 'number', value: 30, required: true, min: 1, placeholder: 'Number of periods' },
    ],
  },
  {
    type: 'strategy',
    subType: 'grid_trading',
    label: 'Grid Trading',
    description: 'Automated grid trading',
    icon: 'Grid3x3',
    color: '#8b5cf6',
    category: 'Strategies',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'lowerPrice', type: 'number', value: 0, required: true, min: 0 },
      { name: 'upperPrice', type: 'number', value: 0, required: true, min: 0 },
      { name: 'gridLevels', type: 'number', value: 10, required: true, min: 2, max: 50 },
      { name: 'investmentAmount', type: 'number', value: 1000, required: true, min: 0 },
    ],
  },
  {
    type: 'strategy',
    subType: 'trailing_stop',
    label: 'Trailing Stop',
    description: 'Dynamic stop loss',
    icon: 'Move',
    color: '#8b5cf6',
    category: 'Strategies',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'trailPercentage', type: 'percentage', value: 5, required: true, min: 0.1, max: 50 },
      { name: 'activationPrice', type: 'number', value: 0, required: false, min: 0 },
    ],
  },

  // INDICATOR BLOCKS
  {
    type: 'indicator',
    subType: 'rsi',
    label: 'RSI Indicator',
    description: 'Relative Strength Index',
    icon: 'Activity',
    color: '#ec4899',
    category: 'Indicators',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'period', type: 'number', value: 14, required: true, min: 2, max: 100 },
      { name: 'overbought', type: 'number', value: 70, required: true, min: 50, max: 100 },
      { name: 'oversold', type: 'number', value: 30, required: true, min: 0, max: 50 },
    ],
  },
  {
    type: 'indicator',
    subType: 'moving_average',
    label: 'Moving Average',
    description: 'SMA/EMA indicator',
    icon: 'TrendingUp',
    color: '#ec4899',
    category: 'Indicators',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'type', type: 'select', value: 'sma', required: true, options: ['sma', 'ema', 'wma'] },
      { name: 'period', type: 'number', value: 20, required: true, min: 2, max: 200 },
    ],
  },
  {
    type: 'indicator',
    subType: 'bollinger_bands',
    label: 'Bollinger Bands',
    description: 'Volatility indicator',
    icon: 'Waves',
    color: '#ec4899',
    category: 'Indicators',
    defaultParameters: [
      { name: 'token', type: 'token', value: '', required: true },
      { name: 'period', type: 'number', value: 20, required: true, min: 2 },
      { name: 'stdDev', type: 'number', value: 2, required: true, min: 1, max: 5, step: 0.1 },
    ],
  },

  // UTILITY BLOCKS
  {
    type: 'loop',
    subType: 'repeat',
    label: 'Loop',
    description: 'Repeat actions',
    icon: 'Repeat',
    color: '#6366f1',
    category: 'Utilities',
    defaultParameters: [
      { name: 'iterations', type: 'number', value: 5, required: true, min: 1, max: 1000 },
      { name: 'delay', type: 'number', value: 1000, required: true, min: 0, placeholder: 'Delay in ms' },
    ],
  },
  {
    type: 'delay',
    subType: 'wait',
    label: 'Delay',
    description: 'Wait before next action',
    icon: 'Timer',
    color: '#6366f1',
    category: 'Utilities',
    defaultParameters: [
      { name: 'duration', type: 'number', value: 5, required: true, min: 0 },
      { name: 'unit', type: 'select', value: 'seconds', required: true, options: ['seconds', 'minutes', 'hours'] },
    ],
  },
];

export const BLOCK_CATEGORIES = [
  'All',
  'Triggers',
  'Conditions',
  'Actions',
  'Strategies',
  'Indicators',
  'Utilities',
];
